### ISSUE TITLE
Sample Request

### ISSUE THREAD

**Issue by RimuruChan** [kairi003/Get-cookies.txt-LOCALLY#3]
Sorry to bother you, do you have any original samples containing malicious code?

**Comment by kairi003** [comment]
Hello,

What you mean by "original" is "Get cookies.txt" that was sending cookies to the server?
That is not my production.
I saved it before it was removed from the store, but it is minified with webpack so it is difficult to read.

**Comment by kairi003** [comment]
I'm closing the Issue as there seems to be no reply. Please reopen if necessary.

**Comment by RimuruChan** [comment]
> Hello,
> 
> What you mean by "original" is "Get cookies.txt" that was sending cookies to the server?
> 
> I am sorry, but that is not my production, nor is that open source, so I think it would be inappropriate to redistribute.
> 
> Also, I saved it before it was removed from the store, but it is minified with webpack so it is difficult to read.

Sorry for late reply. That is what I was looking for. Could you please send me those files?

**Comment by kairi003** [comment]
I'm sorry, but I cannot send it through a public forum because I do not own the copyright for it and it is likely not open-source, so redistribution may not be allowed.

If you have installed the extension and have not uninstalled it, the extension can be found in the installation directory under `bgaddhkoddajcdgocldbbfleckgcbcid`.
Please refer to the README in this repository for the path of the installation directory.

If you have not installed the extension or have already uninstalled it, I think you can only ask a close friend to show it to you privately within a personal scope (I do not assume any legal responsibility for this method). Even if you ask me to send it to you by email, I cannot comply.
